### PR TITLE
Introducing CI!

### PR DESCRIPTION
**Pull request by szepeviktor**
@BinaryMoon Here we go :)

Sample output https://travis-ci.com/szepeviktor/wp-toolbelt/jobs/231577216 (WPCS fails a little bit, use phpcbf)

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please enable TravisCI (the .com version, not the .org) after you merge this PR.

**Comment by szepeviktor** [comment]
Thank you for merging!
No its time to talk you into writing some unit tests :)))

**Comment by szepeviktor** [comment]
> > Please enable TravisCI (the .com version, not the .org) after you merge this PR.
> 
> How do I do this?

Just sign in with GitHub https://travis-ci.com/account/repositories and add this repo BinaryMoon/wp-toolbelt

**Comment by BinaryMoon** [comment]
Oh - I see. You meant not the plugin version of the codebase. Gotcha :)

**Comment by szepeviktor** [comment]
> > Now it's time to talk you into writing some unit tests
> I love the idea of automated testing. I just have no idea how to do it.

Unit test should be a natural part of development (of something important).
I think the learning curve is 1 hour "long", e.g. https://make.wordpress.org/cli/handbook/plugin-unit-tests/ , https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/
Basically 1 positive and one negative (error handling) test per function is more than enough.

```php
// code
function sum($int1, $int2) { return $int1 + $int2 }
// positive unit test
$sum = sum(1, 1);
$this->assertEquals(2, $sum);
// negative test
:) I cannot come up with a failed addition :)
```

**Pull request merged**
