### PR TITLE
[ENH] Add filter for social networks to allow choice in social networks

### PR DESCRIPTION
**Pull request by ndegruchy**
In addition to #98, I've built-in a filter to allow the admin to filter out the list of networks they'd like to present to the end user. This is accomplished by the admin providing a delimited string to the new filter `wp_toolbelt_social_networks`, like so:

```php
function my_social_networks() {
	return 'pocket|wallabag|reddit|email';
}
add_filter( 'wp_toolbelt_social_networks', 'my_social_networks');
```

This is handled by the addition to the `toolbelt_social_networks` function in `module.php`:

```php
	$_default_networks = 'facebook|twitter|linkedin|whatsapp|pinterest|pocket|wallabag|email';

	$desired_networks = explode( '|', apply_filters( 'wp_toolbelt_social_networks', $_default_networks ) );

        ....
	$output = array();

	foreach ( $desired_networks as $item ) {
		if ( array_key_exists( $item, $networks ) ) {
			$output[ $item ] = $networks[ $item ];
		}
	}

	return $output;
```

I'm selfdogfooding this on my own site, and it seems to work well. We could add caching to avoid all this filtering, but it'd be a minor improvement to speed.

### CODE REVIEW

**Comment by BinaryMoon** [comment]
This could work! Thanks for contributing again!

Using this I could limit the default networks and allow users to easily add as many as they like.

What was the reason for the string over an array for the default networks? I'd have probably used an array but if there's a benefit to a string then I'm happy to use that instead.

**Comment by ndegruchy** [comment]
> This could work! Thanks for contributing again!
No problem, I love the plugin, so I wanted to contribute.

> 
> Using this I could limit the default networks and allow users to easily add as many as they like.
> 
> What was the reason for the string over an array for the default networks? I'd have probably used an array but if there's a benefit to a string then I'm happy to use that instead.

Benefit? No, not especially. I found it easier to work with strings last night, especially since I was cribbing from the Shariff interface. Come to think of it, I actually `explode` the string into an array :laughing:.

**Comment by BinaryMoon** [comment]
> Come to think of it, I actually explode the string into an array 😆.

I noticed, that's what made me wonder :)

Cool - I shall merge this as well then!

**Comment by BinaryMoon** [comment]
Hi Nathan - I have merged this and published the plugin update.

I tweaked the social share styles so that they don't squash against each other, and so that they are responsive.

Thanks!

**Pull request merged**
