### PR TITLE
Enhancement: Add "Read it later" services to social sharing menu

### PR DESCRIPTION
**Pull request by ndegruchy**
I added some "read it later" services to the social sharing menu. There is room for more, like Instapaper, but both of these are either open-source or owned by a socially responsible company (like Mozilla).

### CODE REVIEW

**Comment by BinaryMoon** [comment]
Thanks for the pull request.

How big is Wallabang? I haven't heard of them before. It looks like they are Italian specific?

I like the idea of adding more links but I wonder if it will be too many? Perhaps there should be a default set and then a simple way to enable more.

I quite like the simplicity of the current collection, and I don't know if everyone would want the full list. What do you think?

**Comment by ndegruchy** [comment]
How big is Wallabang? I haven't heard of them before. It looks like they are Italian specific?

Wallabag is a popular self-hosted, open source and in this specific case, a developer hosted read-later program. The developer is Italian, I believe. Hard to say how big the service is, though.


I like the idea of adding more links but I wonder if it will be too many? Perhaps there should be a default set and then a simple way to enable more.

I quite like the simplicity of the current collection, and I don't know if everyone would want the full list. What do you think?

Agreed. I actually used CSS Grids to make it a bit more manageable. That being said, Shariff takes a delimiter approach to specifying which accounts to present. Maybe something like that? Maybe a filter to determine what to display? The wiki says to use the `display: none` to hide ones you don’t need. Maybe that is the method to use?

Thanks!

—
Nathan DeGruchy

On Jul 8, 2020, at 18:30, Ben Gillbanks <notifications@github.com> wrote:

﻿

Thanks for the pull request.

How big is Wallabang? I haven't heard of them before. It looks like they are Italian specific?

I like the idea of adding more links but I wonder if it will be too many? Perhaps there should be a default set and then a simple way to enable more.

I quite like the simplicity of the current collection, and I don't know if everyone would want the full list. What do you think?

**Comment by BinaryMoon** [comment]
Thanks. I think I will merge it and consider how best to approach the extra content before I publish the update. I don't want to have loads of new options pop up and surprise people :)

Perhaps I'll hide them by default (using CSS) and then add info to the docs about what is available and how to make them available.

**Comment by ndegruchy** [comment]
Sorry for a bit of necromancy here, but I've been kicking around how to implement a selection of social networks (or the ability to add your own). What if an admin were to build a filter something like this:

```php
function my_social_networks( $networks ) {
    array_filter( $networks, function ( $network ) {
        return ( $network != "Facebook" );
    } );
}
add_filter( 'wp_toolbelt_social_sharing_filter', 'my_social_networks', 1 );
```

Of course, adding something like this to `module.php`:

```php
$filtered = apply_filters( 'wp_toolbelt_social_sharing_filter', $networks );

if ( ( ! is_array( $filtered ) ) || ( empty( $filtered ) ) ) {
	return $networks;
} else {
	return $filtered;
}
```

OR, maybe crib from Shariff and use a delimited list and just run through the items:

```php
function my_social_networks() {
    return 'facebook|linkedin|pocket';
}
add_filter( 'wp_toolbelt_social_sharing_filter', 'my_social_networks');
```

And in `module.php`:

```php
function toolbelt_social_networks() {
    $desired_networks = apply_filters( 'wp_toolbelt_social_sharing_filter', 'facebook|twitter|linkedin|whatsapp|pinterest|pocket|wallabag|reddit|email' );
    
    $desired_networks = explode( '|', $desired_networks );
    
    $output = array();
    
    foreach( $desired_networks as $item ) {
        if( array_key_exists( $item, $networks ) ) {
          $output[$item] = $networks[$item];
        }
    }
    
    return $output;

}
```

I dunno, just spitballing.

**Comment by BinaryMoon** [comment]
I've commented on the pull request but I like the idea :)

**Pull request merged**
