### PR TITLE
Fix php 7.3 conflict

### PR DESCRIPTION
**Pull request by szepeviktor**
... I plan to release WP stubs **without** compat thingies

### CODE REVIEW

**Comment by szepeviktor** [comment]
@BinaryMoon All 🍏

**Comment by BinaryMoon** [comment]
This is great - thanks :)

Unfortunately there's a conflict - could you fix that please?

**Comment by szepeviktor** [comment]
Done.

**Comment by szepeviktor** [comment]
This is OK
Some functions are not loaded during static analysis

**Comment by szepeviktor** [comment]
Two Things for you :)

1. index.php as the module's main file could be named main.php or module.php
1. you could send code to the repo by a PR only, it is highly beneficial

**Comment by BinaryMoon** [comment]
> index.php as the module's main file could be named main.php or module.php

You mean to rename the module files? Yeah - I don't mind doing that. Probably module.php

> you could send code to the repo by a PR only, it is highly beneficial

I don't understand what you mean by that?

**Comment by szepeviktor** [comment]
> > you could send code to the repo by a PR only, it is highly beneficial
> 
> I don't understand what you mean by that?

1. Open a new branch
1. Commit the code there
1. Open a PR, assign it to yourself
1. Wait for "the green" (Travis CI)
1. Merge!
1. Sleep well at night :)

**Comment by szepeviktor** [comment]
When number 4 is "the red" -> you need more commits :)

**Comment by BinaryMoon** [comment]
So work in a branch then merge so I don't introduce build errors. Makes sense.

**Comment by szepeviktor** [comment]
Now you have a pretty robust code base :)

Please take a look at https://github.com/lucatume/wp-browser - it makes is really easy to add tests.

**Comment by BinaryMoon** [comment]
Thanks for your help! It does feel a lot more robust now!

I tried raising the phpstan test level to 5 yesterday but it gave me a single error that didn't make sense (at the time). I think I may have worked out a solution though so will likely try again.

Regarding tests, I'm not sure it will be that easy for me. I'm not using classes, and a lot of the functions are outputting data or manipulating html, and some of them are pulling things from databases.

There's very few (possibly no) pure functions that take an input and return something.

**Comment by szepeviktor** [comment]
I think recognizing this will help much more than writing tests.

**Pull request merged**
