### PR TITLE
Use array_* function in contact_cpt_status

### PR DESCRIPTION
**Pull request by szepeviktor**
instead of temp. vars. and for loop

### CODE REVIEW

**Comment by szepeviktor** [comment]
This is only an example

please watch https://www.youtube.com/watch?v=crSUWtRYw-M

**Comment by BinaryMoon** [comment]
interesting - thanks. I've seen similar things with javascript and the array map function.

**Comment by szepeviktor** [comment]
> I've seen similar things with javascript and the array map function.

Yes those things are so similar they are the same :)

**Comment by BinaryMoon** [comment]
I've made other changes to the module-ajax function so there are conflicts. So I have merged this manually and will close the pull request.

Thanks!

**Comment by szepeviktor** [comment]
All right.
This is not really meant to be merged.

**Comment by BinaryMoon** [comment]
It's ok to merge it though isn't it? It works and it's shorter code - which I like.

**Comment by szepeviktor** [comment]
It lacks a semicolon, and here only for the video.

**Comment by BinaryMoon** [comment]
I did spot the missing semicolon :)

**Comment by szepeviktor** [comment]
This PR is for learning to hate

- for loops
- conditionals
- temp vars.

**Comment by BinaryMoon** [comment]
I will watch the video!

**Comment by szepeviktor** [comment]
https://www.php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration

PHP 7 has a plethora of new features.

```php
function doit(): I'm_return_typehint
{
}
```

Please study this page https://www.php.net/manual/en/language.oop5.changelog.php

**Pull request closed without merging**
