### PR TITLE
phpstan-shim is a thing of the past

### PR DESCRIPTION
**Pull request by szepeviktor**
used to get PHPStan in a PHAR file, now phpstan/phpstan is also distributed as a PHAR file

@BinaryMoon

### CODE REVIEW

**Comment by szepeviktor** [comment]
PHPStan 0.12 needs more typehints!

See https://medium.com/@ondrejmirtes/phpstan-0-12-released-f1a88036535d
Now Level 6 does something else.

Please add those it it is possible.

**Comment by BinaryMoon** [comment]
Thanks Viktor. Why did you remove the vendor exclusion? I don't want to test code that's not mine.

**Comment by szepeviktor** [comment]
PHPStan tests what it is instructed to

```
    paths:
        - %currentWorkingDirectory%/modules/
        - %currentWorkingDirectory%/admin/
```

**Comment by BinaryMoon** [comment]
Ah ha - got it. Thanks.

**Comment by BinaryMoon** [comment]
I don't understand how to fix the typehint errors mentioned in the merged code.
https://travis-ci.com/BinaryMoon/wp-toolbelt/jobs/264364116

I thought I had worked it out by looking at the docs here:
https://www.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration

And I made some changes to add `@return void` and `array $param` (https://github.com/BinaryMoon/wp-toolbelt/commit/cc907b4f6f273674fa79186691ef7df1e0fd9822) but the errors don't seem to have changed. Is there an example of what I should be doing instead?

**Comment by ondrejmirtes** [comment]
@BinaryMoon Latest version gives you some hints. Instead of `array`, you should specify what's in the array. Like this: `Foo[]` or this: `array<Foo>`.

If you don't want to specify it, you can use explicit mixed: `mixed[]` or `array<mixed>`.

**Comment by szepeviktor** [comment]
and the *secret* array shapes: `array{tag: string, priority: int}`

**Comment by BinaryMoon** [comment]
Thanks! :)

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
